# Generated by Django 3.2.9 on 2021-11-09 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211026_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuelabel',
            name='short_name',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectIssueLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=10)),
                ('short_name', models.CharField(max_length=5)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'verbose_name': 'Project Issue Label',
                'verbose_name_plural': 'Projects Issues Label',
            },
        ),
    ]
