# Generated by Django 3.2.9 on 2021-12-08 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_collaborators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='desc',
        ),
    ]
