# Generated by Django 3.2.9 on 2021-12-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_project_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(),
        ),
    ]
