# Generated by Django 3.2.8 on 2021-10-21 13:22

import bugtail.helpers.image_helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=bugtail.helpers.image_helper.get_upload_path),
        ),
    ]
